# General
name: IDAN.GOLDMAN.WORK
title: Idan Goldman
description: Experienced Frontend Developer
author: idan_goldman
email: reply@goldman.work

# Front Matter Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Collections
collections:
  posts:
    permalink: /notebook/:title/

# Permalinks
url: 'https://idan.goldman.work'
baseurl: ''
host: idan.goldman.local
port: 1234

# Build settings
source: ./source
destination: ./public
exclude: [assets/scss]
keep_files: [assets/css]
markdown: kramdown
timezone: Asia/Jerusalem

# Plugins
plugins:
  # - jekyll-inline-svg
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-tidy

# HTML Compression
jekyll_tidy:
  ignore_env: development
  compress_html: true

# SASS
# sass:
#   style: compressed
#   load_paths:
#     - ../kit

# SVG
# svg:
#   optimize: true
#
# social_icons_folder_path: /assets/images/social-icons/
