# General
name: Idan Goldman
title: Welcome to my portfolio website!
description: Bootstrapper and Frontend Developer
author: idan_goldman
email: reply@goldman.work

# Collections
collections:
  posts:
    permalink: /notebook/:title/
    layout: post

# Front Matter Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Permalinks
url: 'https://idan.goldman.work'
baseurl: ''
host: idan.goldman.local
port: 1234

# Build settings
source: ./source
destination: ./public
exclude: [assets/scss]
keep_files: [assets/css]
markdown: kramdown
timezone: Asia/Jerusalem

# Plugins
plugins:
  - jekyll-feed
  - jekyll-inline-svg
  - jekyll-last-modified-at
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-tidy

# SASS
# sass:
#   style: compressed
#   load_paths:
#     - ../kit

# HTML Compression
jekyll_tidy:
  ignore_env: development
  compress_html: true

# SVG
svg:
  optimize: true

social_icons_folder_path: /assets/images/social-icons/
